# Generated by Django 5.2.8 on 2025-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('Собирается', 'Собирается'), ('В пути', 'В пути'), ('Доставлен в пунк выдачи', 'Доставлен в пункт выдачи')], default='Оформлен', max_length=50),
        ),
    ]
